apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlink-service
  labels:
    app: shortlink-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortlink-service
  template:
    metadata:
      labels:
        app: shortlink-service
    spec:
      containers:
      - name: shortlink-service
        image: khaledelnabawy1/shortlink-service:6
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: shortlink-service-svc
spec:
  type: LoadBalancer
  selector:
    app: shortlink-service
  ports:
    - port: 80
      targetPort: 3000
